In [2]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

Matplotlib is building the font cache; this may take a moment.

In [3]:
Path("../data/raw").mkdir(parents=True, exist_ok=True)
Path("../data/processed").mkdir(parents=True, exist_ok=True)
Path("../outputs/figures").mkdir(parents=True, exist_ok=True)

In [6]:
def fetch_worldbank_indicator(country_code, indicator_code):
    """
    Fetch one World Bank indicator for one country.
    
    country_code: for India, use 'IND'
    indicator_code: for diabetes prevalence, use 'SH.STA.DIAB.ZS'
    """
    url = f"https://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_code}"
    
    params = {
        "format": "json",
        "per_page": 20000
    }
    
    response = requests.get(url, params=params)
    response.raise_for_status()
    
    data = response.json()[1]
    
    rows = []
    for item in data:
        rows.append({
            "country": item["country"]["value"],
            "country_code": item["countryiso3code"],
            "year": int(item["date"]),
            "indicator": item["indicator"]["value"],
            "indicator_code": item["indicator"]["id"],
            "value": item["value"]
        })
    
    df = pd.DataFrame(rows)
    return df

In [7]:
diabetes_df = fetch_worldbank_indicator(
    country_code="IND",
    indicator_code="SH.STA.DIAB.ZS"
)

diabetes_df.head()

,country,country_code,year,indicator,indicator_code,value
0,India,IND,2025,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
1,India,IND,2024,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,10.5
2,India,IND,2023,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
3,India,IND,2022,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
4,India,IND,2021,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN

In [8]:
diabetes_df.info()
diabetes_df.sort_values("year").tail(10)

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         66 non-null     str
 1   country_code    66 non-null     str
 2   year            66 non-null     int64
 3   indicator       66 non-null     str
 4   indicator_code  66 non-null     str
 5   value           2 non-null      float64
dtypes: float64(1), int64(1), str(4)
memory usage: 3.2 KB

,country,country_code,year,indicator,indicator_code,value
9,India,IND,2016,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
8,India,IND,2017,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
7,India,IND,2018,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
6,India,IND,2019,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
5,India,IND,2020,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
4,India,IND,2021,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
3,India,IND,2022,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
2,India,IND,2023,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN
1,India,IND,2024,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,10.5
0,India,IND,2025,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN